---
# Use container-based infrastructure
sudo: false

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

jdk: oraclejdk7

scala: 2.11.6

script:
  - sbt clean coverage test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success: "sbt coveralls"

matrix:
  include:
    # Base: test with mock

    # test with real redis-server
    - scala: 2.11.6
      env: USE_REAL_REDIS="yes"
      services:
        - redis-server

